name: Create Docker Image for Carrier Changes Subscriber

on: 
  workflow_dispatch:
    inputs:
      deployment_id:
        required: false
        default: '0'
        
  repository_dispatch:
    types: create-firmware

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'
        ref: feature/iot-adu
    - name: esp-idf build
      uses: espressif/esp-idf-ci-action@v1
      with:
        esp_idf_version: v4.4
        target: esp32s2
        path: 'demos/projects/ESPRESSIF/adu/'
