name: Deploy over Azure

on: 
  workflow_dispatch:
    inputs:
      deployment_id:
        required: false
        default: '0'
        
  repository_dispatch:
    types: create-firmware

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'
        ref: feature/iot-adu
    - uses: azure/login@v1
      with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
