name: Deploy over Azure

on: 
  workflow_dispatch:
    inputs:
      deployment_id:
        required: false
        default: '0'
        
  repository_dispatch:
    types: create-firmware

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'
        ref: feature/iot-adu
    - name: esp-idf build
      uses: espressif/esp-idf-ci-action@v1
      with:
        esp_idf_version: v4.3
        target: esp32
        path: 'demos/projects/ESPRESSIF/adu/'
    - uses: azure/login@v1
      with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          
    - name: Upload to blob storage
      uses: azure/CLI@v1
      with:
        inlineScript: |
            az storage blob upload --account-name rgtestjanstorageacc --auth-mode key -c espressif-esp32-azure-iot-kit-1-3 -f demos/projects/ESPRESSIF/adu/build/azure_iot_freertos_esp32.bin -n azure_iot_freertos_esp32-v1.9.bin
